### ISSUE TITLE
Can I use it for pyqt5?

### ISSUE THREAD

**Issue by duolabmeng6** [macmade/GitHubUpdates#110]
Can I use it for pyqt5?

**Comment by macmade** [comment]
You can probably find a way, but why?

**Comment by duolabmeng6** [comment]
I'm sorry to raise this question because I couldn't find a solution with Google.

**Comment by macmade** [comment]
You should probably try to find something equivalent in Python or QT.

**Comment by duolabmeng6** [comment]
> You should probably try to find something equivalent in Python or QT.

I'm sorry I've searched all over Google and Bing. I can't find a pure python solution. I found yours.[GitHubUpdates](https://github.com/macmade/GitHubUpdates)It seems relatively simple.[Sparkle](https://github.com/sparkle-project/Sparkle)
I don't know if you use pyqt If there is any use, I would like to get your help ~ ~

**Comment by macmade** [comment]
I don't know PyQT, so I cannot really help.

The project can be used from Swift and Objective-C.  
You should be able to use it from C++, using Objective-C++, but that's all I can tell.

**Comment by duolabmeng6** [comment]
Thank you very much for your answer. Thank you.

**Comment by duolabmeng6** [comment]
Thank you very much for your help

Since it can't be used and the principle of automatic update is not complicated, I built a wheel myself

I hope it can help people who need pyqt application to update automatically

https://github.com/duolabmeng6/qtAutoUpdateApp

Support MacOS system application update

Support window system application update

No server required

Use GitHub to automatically build and publish software

The client automatically checks the software resources published in GitHub and updates them automatically

Use the image to optimize the domestic network to avoid the failure to download updates
